version: "3"
services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250"

  otel-collector:
    build:
      context: ../..
      dockerfile: examples/tracing/Dockerfile
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    depends_on:
      - jaeger

  tracegen:
    build:
      context: ../../tracegen
    command:
      - -otlp-endpoint
      - otel-collector:4317
      - -otlp-insecure
      - -rate
      - "1"
      - -duration
      - 10000000s
    depends_on:
      - otel-collector
